main/urls.py
from django.urls import path
from main.views import show_main, create_product, register, login_user, logout_user, delete_product, increase_product, decrease_product, edit_product, show_xml, show_json, show_xml_by_id, show_json_by_id, get_product_json, add_product_ajax, delete_product_ajax, create_product_flutter

# Deploy ulang

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('delete_product/<int:product_id>/', delete_product, name='delete_product'),
    path('increase_product/<int:product_id>/', increase_product, name='increase_product'),
    path('decrease_product/<int:product_id>/', decrease_product, name='decrease_product'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-ajax/', add_product_ajax, name='add_product_ajax'),
    path('delete-ajax/', delete_product_ajax, name='delete_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

pachill_market/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name_1 = models.CharField(max_length=255)
    name_2 = models.CharField(max_length=255, default="-")
    date_added = models.DateField(auto_now_add=True)
    price = models.IntegerField(default=0)
    amount = models.IntegerField(default=0)
    description = models.TextField()

main/forms.py
from django import forms
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name_1", "price", "amount", "description"]
        labels = {
            "name_1": "Nama Produk",
            "price": "Harga Produk",
            "amount": "Jumlah Produk",
            "description": "Deskripsi Produk",
        }

main/views.py
import datetime
import json
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, HttpResponseNotAllowed
from django.http import JsonResponse
from django.core import serializers
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages  
from main.forms import ProductForm
from .models import Product

# Deploy ulang

@login_required(login_url='/login')
# Create your views here.
def show_main(request):
    products = Product.objects.filter(user=request.user)
    jumlah_total = sum(product.amount for product in products)

    context = {
        # Nama yang membuat update terakhir
        'nama_updater': 'Ramadhan Andika Putra (2206081976) - PBP A',

        'jumlah_total': jumlah_total,
        'products': products,
        'name': request.user.username,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    else:
        form = ProductForm()

    context = {
        'form': form,
        'name': request.user.username,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "create_product.html", context)

def delete_product(request, product_id):
    try:
        product = Product.objects.get(id=product_id)
        product.delete()
        return redirect('main:show_main')
    except Product.DoesNotExist:
        # Handle jika produk tidak ditemukan
        pass

def increase_product(request, product_id):
    try:
        product = Product.objects.get(id=product_id)
        product.amount += 1
        product.save()
        return redirect('main:show_main')
    except Product.DoesNotExist:
        # Handle jika produk tidak ditemukan
        pass

def decrease_product(request, product_id):
    try:
        product = Product.objects.get(id=product_id)
        if product.amount > 0:
            product.amount -= 1
            product.save()
        return redirect('main:show_main')
    except Product.DoesNotExist:
        # Handle jika produk tidak ditemukan
        pass

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {
        'form': form,
        'name': request.user.username,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "edit_product.html", context)

@csrf_exempt
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun kamu sudah berhasil dibuat!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            last_login_time = datetime.datetime.now().replace(microsecond=0)  # Removes microseconds
            formatted_last_login = last_login_time.strftime('%Y-%m-%d %H:%M:%S')  # Formats to string with desired format
            response.set_cookie('last_login', formatted_last_login)
            return response
        else:
            messages.info(request, 'Maaf, username atau password yang anda berikan salah. Mohon coba lagi! :D')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def get_product_json(request):
    product_item = Product.objects.all()
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name_1 = request.POST.get("name_1")
        price = request.POST.get("price")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(name_1=name_1, price=price, amount=amount, description=description, user=user)
        new_product.save()

        jumlah_total = sum(product.amount for product in Product.objects.filter(user=request.user))

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_product_ajax(request):
    if request.method == 'DELETE':
        product_id = request.GET.get('id')  # get id from the query parameter
        try:
            product = Product.objects.get(id=product_id, user=request.user)
            product.delete()
            jumlah_total = sum(product.amount for product in Product.objects.filter(user=request.user))
            return JsonResponse({'status': 'success', 'message': 'Produk berhasil dihapus'}, status=200)
        except Product.DoesNotExist:
            return JsonResponse({'status': 'error', 'message': 'Produk tidak ditemukan'}, status=404)
        except Exception as e:
            return JsonResponse({'status': 'error', 'message': str(e)}, status=500)
    else:
        return HttpResponseNotAllowed(['DELETE'])
    
@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            # Tambahkan validasi data di sini jika perlu

            new_product = Product.objects.create(
                user = request.user,
                name1 = data.get("name1"), # Pastikan ini sesuai dengan field di model
                price = data.get("price"),
                amount = data.get("amount"),
                description = data.get("description")
            )
            new_product.save()

            return JsonResponse({"status": "success"}, status=200)
        except Exception as e:
            # Tangkap kesalahan dan kirimkan sebagai respons
            return JsonResponse({"status": "error", "message": str(e)}, status=400)
    else:
        return JsonResponse({"status": "error", "message": "Invalid request"}, status=401)

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}

<link href="https://fonts.googleapis.com/css2?family=Uni+Sans:wght@400;700&display=swap" rel="stylesheet">

<style>
    /* Mengubah font menjadi "Uni Sans" */
    .navbar, .navbar-nav .nav-link {
        font-family: 'Uni Sans', sans-serif;
    }

    /* Memperbesar ukuran teks dari "Pachill Market" */
    .navbar-brand {
        font-size: 32px;
        font-family: 'Uni Sans Heavy Italic CAPS', sans-serif;
        font-weight: 700;
        font-style: italic;
    }

    .text-blue {
    color: rgb(0, 94, 255);
    }

    body {
    background-color: rgb(232, 237, 255);
    }

    /* Memberikan margin atas pada container-fluid */
    #content-container {
        margin-top: 20px; /* Sesuaikan margin */
    }

    /* Menghapus margin atas pada navbar */
    .navbar {
        margin-top: 0;
    }

    /* Warna awal button */
    .btn-logout {
        background-color: transparent;
        color: red;
    }

    /* Warna saat tombol di-hover */
    .btn-logout:hover {
        background-color: red;
        color: white;
    }

    h1 {
        margin: 20px 0;
        text-align: center;
    }

    form {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        margin-top: 40px;
    }

    table {
        width: 60%;
        margin: 0 auto;
    }

    table td {
        padding: 10px;
    }

    input[type="submit"] {
        padding: 10px 20px;
        background-color: rgb(0, 94, 255);
        color: white;
        border: none;
        cursor: pointer;
        border-radius: 5px;
    }

    input[type="submit"]:hover {
        background-color: rgb(0, 74, 205);
    }
</style>

<nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
    <div class="container-fluid">
    <a class="navbar-brand mb-0 h1" href="#">
        <span class="text-black">Pachill</span><span class="text-blue">.Market</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'main:show_main' %}">[Home]</a>
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </div>
        </div>

        <div class="ms-auto d-flex align-items-center">
        <span style="margin-right: 15px;">
            You're logged in as <strong>{{ name }}</strong>!</br>
            <small>Last login: {{ last_login }}</small>
        </span>
        <a href="{% url 'main:logout' %}">
          <button class="btn btn-outline-success btn-logout" type="submit" style="border-color: red;">Log Out</button>
        </a>
    </div>
    </div>
</nav>

<div class="container-fluid h-100" id="content-container"> 
    <div class="row h-100 justify-content-center align-items-center"> 
        <div class="col-md-6">
            <div class="card bg-light p-4">
                <h1 class="text-center mb-4">Tambah Produk Baru</h1>

                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    </br>
                    <div class="text-center">
                        <input type="submit" value="Tambahkan Produk"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %} 

{% block content %}

<link href="https://fonts.googleapis.com/css2?family=Uni+Sans:wght@400;700&display=swap" rel="stylesheet">

<style>
    /* Mengubah font menjadi "Uni Sans" */
    .navbar, .navbar-nav .nav-link {
        font-family: 'Uni Sans', sans-serif;
    }

    /* Memperbesar ukuran teks dari "Pachill Market" */
    .navbar-brand {
        font-size: 32px;
        font-family: 'Uni Sans Heavy Italic CAPS', sans-serif;
        font-weight: 700;
        font-style: italic;
    }

    .text-blue {
    color: rgb(0, 94, 255);
    }

    body {
    background-color: rgb(232, 237, 255);
    }

    /* Memberikan margin atas pada container-fluid */
    #content-container {
        margin-top: 20px; /* Sesuaikan dengan margin yang Anda inginkan */
    }

    /* Menghapus margin atas pada navbar */
    .navbar {
        margin-top: 0;
    }

    /* Warna awal button */
    .btn-logout {
        background-color: transparent;
        color: red;
    }

    /* Warna saat tombol di-hover */
    .btn-logout:hover {
        background-color: red;
        color: white;
    }

    h1 {
        margin: 20px 0;
        text-align: center;
    }

    form {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        margin-top: 40px;
    }

    table {
        width: 60%;
        margin: 0 auto;
    }

    table td {
        padding: 10px;
    }

    input[type="submit"] {
        padding: 10px 20px;
        background-color: rgb(0, 94, 255);
        color: white;
        border: none;
        cursor: pointer;
        border-radius: 5px;
    }

    input[type="submit"]:hover {
        background-color: rgb(0, 74, 205);
    }
</style>

<nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
    <div class="container-fluid">
    <a class="navbar-brand mb-0 h1" href="#">
        <span class="text-black">Pachill</span><span class="text-blue">.Market</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'main:show_main' %}">[Home]</a>
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </div>
        </div>

        <div class="ms-auto d-flex align-items-center">
        <span style="margin-right: 15px;">
            You're logged in as <strong>{{ name }}</strong>!</br>
            <small>Last login: {{ last_login }}</small>
        </span>
        <a href="{% url 'main:logout' %}">
          <button class="btn btn-outline-success btn-logout" type="submit" style="border-color: red;">Log Out</button>
        </a>
    </div>
    </div>
</nav>

<div class="container-fluid h-100" id="content-container"> 
    <div class="row h-100 justify-content-center align-items-center"> 
        <div class="col-md-6">
            <div class="card bg-light p-4">
                <h1 class="text-center mb-4">Edit Informasi Produk</h1>

                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    </br>
                    <div class="text-center">
                        <input type="submit" value="Edit Produk"/>>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<link href="https://fonts.googleapis.com/css2?family=Uni+Sans:wght@400;700&display=swap" rel="stylesheet">

<style>
    /* Mengubah font menjadi "Uni Sans" */
    .navbar, .navbar-nav .nav-link {
        font-family: 'Uni Sans', sans-serif;
    }

    /* Memperbesar ukuran teks dari "Pachill Market" */
    .navbar-brand {
        font-size: 32px;
        font-family: 'Uni Sans Heavy Italic CAPS', sans-serif;
        font-weight: 700;
        font-style: italic;
    }

    .text-blue {
    color: rgb(0, 94, 255);
    }

    body {
    background-color: rgb(232, 237, 255);
    }

    /* Memberikan margin atas pada container-fluid */
    #content-container {
        margin-top: 20px; /* Sesuaikan dengan margin yang Anda inginkan */
    }

    /* Menghapus margin atas pada navbar */
    .navbar {
        margin-top: 0;
    }
</style>

<nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
    <div class="container-fluid">
    <a class="navbar-brand mb-0 h1" href="#">
        <span class="text-black">Pachill</span><span class="text-blue">.Market</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'main:login' %}">[Home]</a>
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </div>
        </div>
    </div>
    </div>
</nav>

<div class="container-fluid h-100" id="content-container"> <!-- Menggunakan container-fluid dan h-100 untuk fullscreen -->
    <div class="row h-100 justify-content-center align-items-center"> <!-- Menggunakan row dan justify-content-center align-items-center untuk rata tengah -->
        <div class="col-md-4"> <!-- Menggunakan col-md-4 untuk lebar konten yang baik -->
            <div class="card bg-light p-4"> <!-- Menambahkan kelas card, bg-light untuk latar belakang cerah, dan p-4 untuk padding -->
                <h1 class="text-center mb-4">Login</h1>

                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="username" class="form-label">Username:</label>
                        <input type="text" name="username" id="username" class="form-control" placeholder="Username">
                    </div>

                    <div class="mb-3">
                        <label for="password" class="form-label">Password:</label>
                        <input type="password" name="password" id="password" class="form-control" placeholder="Password">
                    </div>

                    <div class="text-center">
                        <button class="btn btn-primary" type="submit">Login</button>
                    </div>
                </form>

                {% if messages %}
                    <div class="mt-3">
                        <ul>
                            {% for message in messages %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}     
                
                <p class="mt-3 text-center">Apakah kamu belum mempunyai akun?</br> <a href="{% url 'main:register' %}">Segera daftar sekarang!</a></p>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
<!-- Deploy Ulang, pls bisa -->
<link href="https://fonts.googleapis.com/css2?family=Uni+Sans:wght@400;700&display=swap" rel="stylesheet">

<style>
    /* Mengubah font menjadi "Uni Sans" */
    .navbar, .navbar-nav .nav-link {
        font-family: 'Uni Sans', sans-serif;
    }

    /* Memperbesar ukuran teks dari "Pachill Market" */
    .navbar-brand {
        font-size: 32px;
        font-family: 'Uni Sans Heavy Italic CAPS', sans-serif;
        font-weight: 700;
        font-style: italic;
    }

    .text-blue {
    color: rgb(0, 94, 255);
    }

    body {
    background-color: rgb(232, 237, 255);
    }

    /* Memberikan margin atas pada container-fluid */
    #content-container {
        margin-top: 20px; /* Sesuaikan dengan margin yang Anda inginkan */
    }

    /* Menghapus margin atas pada navbar */
    .navbar {
        margin-top: 0;
    }

    /* Warna awal button */
    .btn-logout {
        background-color: transparent;
        color: red;
    }

    /* Warna saat tombol di-hover */
    .btn-logout:hover {
        background-color: red;
        color: white;
    }

    .different-color {
    background-color: rgb(240, 255, 238);
    border: 1px solid rgb(0, 94, 255);
    }

    /* Memberikan margin atas pada container-display */
    #content-display {
        margin-top: 20px; /* Sesuaikan dengan margin yang Anda inginkan */
    }

    /* Memberikan margin atas pada container-fluid */
    #last-updater {
        margin-top: 20px; /* Sesuaikan dengan margin yang Anda inginkan */
    }
</style>

<nav class="navbar navbar-expand-lg bg-light" data-bs-theme="light">
    <div class="container-fluid">
    <a class="navbar-brand mb-0 h1" href="#">
        <span class="text-black">Pachill</span><span class="text-blue">.Market</span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" aria-current="page" href="{% url 'main:show_main' %}">[Home]</a>
                <a class="nav-link active" aria-current="page" href="{% url 'main:create_product' %}">[Tambah Produk Baru]</a>
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
            </div>
        </div>

        <div class="ms-auto d-flex align-items-center">
        <span style="margin-right: 15px;">
            Welcome, <strong>{{ name }}</strong>!</br>
            <small>Last login: {{ last_login }}</small>
        </span>
        <a href="{% url 'main:logout' %}">
          <button class="btn btn-outline-success btn-logout" type="submit" style="border-color: red;">Log Out</button>
        </a>
    </div>
    </div>
</nav>

<div class="container-fluid h-100" id="content-display">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-md-6 bg-light p-4 text-center">
            <h1 class="text-center mb-4">Pachill Market Stock Manager</h1>
            <p class="text-center">
                Platform pengelola stok supermarket idaman kamu :D
            </p>
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Tambah Produk by AJAX</button>
        </div>
    </div>
  </div>  


  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name_1" class="col-form-label">Nama Produk:</label>
                        <input type="text" class="form-control" id="name_1" name="name_1"></input>
                    </div>
                    <div class="mb-3">
                        <label for="price" class="col-form-label">Harga Produk:</label>
                        <input type="number" class="form-control" id="price" name="price"></input>
                    </div>
                    <div class="mb-3">
                        <label for="amount" class="col-form-label">Jumlah Produk:</label>
                        <input type="number" class="form-control" id="amount" name="amount"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Deskripsi Produk:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                    </div>
            </div>
        </div>
    </div>
  </div>

</br>

<div id="product-list" class="row h-100 justify-content-center align-items-center">
    <!-- Elemen baru untuk menampung daftar produk -->
</div>


<!-- Informasi Produk -->
<div class="my-3 text-center">
    <strong>Total Jenis Produk Yang Masuk:</strong> 
    <span id="totalJenisProduk">{{ products|length }} jenis produk</span>
</div>
<div class="my-3 text-center">
    <strong>Jumlah Total Produk yang Tersimpan:</strong> 
    <span>{{ jumlah_total }} buah</span>
</div>

<div class="container-fluid h-100" id="last-updater">
   <div class="row h-100 justify-content-center align-items-center">
      <div class="col text-center">
          <div class="my-3">
             <i>Last updated by: {{ nama_updater }}</i>
                  </div>
       </div>
  </div>
</div>

  <script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }

    async function refreshProducts() {
        const productList = document.getElementById("product-list");
        
        productList.innerHTML = "";  

        const products = await getProducts();
        
        document.getElementById("totalJenisProduk").innerText = `${products.length} jenis produk`;
        
        let cardHtmlString = "";

        products.forEach((item, index) => {
            let cardClass = "";
            if (index === products.length - 1) {
                cardClass = "different-color";
            }

            cardHtmlString += `
            <div class="col-md-4 mb-4">
                <div class="card ${cardClass}">
                    <div class="card-body">
                        <h5 class="card-title">${item.fields.name_1}</h5>
                        <p class="card-text">${item.fields.description}</p>
                        <p><strong>Harga Produk:</strong> Rp. ${item.fields.price},-</p>
                        <p><strong>Jumlah Produk:</strong> ${item.fields.amount}</p>
                        <p><strong>Tanggal Produk Masuk:</strong> ${item.fields.date_added}</p>
                        <div class="text-center">
                            <button class="btn btn-danger delete-product" data-product-id="${item.pk}">Hapus by AJAX</button>
                        </div>
                    </div>
                </div>
            </div>
            `;
        });

        productList.innerHTML = `<div class="row h-100 justify-content-center align-items-center">${cardHtmlString}</div>`;
  
        const deleteButtons = document.querySelectorAll('.delete-product');
        deleteButtons.forEach(button => {
            button.addEventListener('click', (e) => {
                const productId = e.target.getAttribute('data-product-id');
                deleteProduct(productId);
            });
        });
    }
    refreshProducts()

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }
    document.getElementById("button_add").onclick = addProduct

    async function deleteProduct(productId) {
        const url = `{% url 'main:delete_product_ajax' %}?id=${productId}`;
        const response = await fetch(url, { method: 'DELETE' });
        if (response.ok) {
            refreshProducts();
        }
    }
  </script>
  
{% endblock content %}